//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StellerAcunMedyaAkademiPortfolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StellerAcunMedyaDBEntities : DbContext
    {
        public StellerAcunMedyaDBEntities()
            : base("name=StellerAcunMedyaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Testimonial> TBL_Testimonial { get; set; }
        public virtual DbSet<TBL_About> TBL_About { get; set; }
        public virtual DbSet<TBL_Contact> TBL_Contact { get; set; }
        public virtual DbSet<TBL_Message> TBL_Message { get; set; }
        public virtual DbSet<TBL_Project> TBL_Project { get; set; }
        public virtual DbSet<TBL_Service> TBL_Service { get; set; }
        public virtual DbSet<TBL_Skill> TBL_Skill { get; set; }
        public virtual DbSet<TBL_SocialMedia> TBL_SocialMedia { get; set; }
        public virtual DbSet<TBL_Feature> TBL_Feature { get; set; }
        public virtual DbSet<TBL_Admin> TBL_Admin { get; set; }
    }
}
